language: node_js
node_js:
- '10'
dist: trusty
sudo: required
before_script:
- npm install -g eslint
- npm install --no-optional
cache:
  directories:
  - node_modules
env:
- NODE_ENV=ci
script:
- sleep 5
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: KZvJ8x0xYuVhIDnEiVjIBhE1OYQHQszIQo+eOXdg29G5un/fIAkiCT/+25ZBBJR+bWEDwuTCl5QOcw2/ZmaUUVG5G5elhjm112CMK78RipA18Ri4tmr3sRnunt+1EwmB//y0CjvdKkt1twcthnTECs+arugoamS9BSxmHroedqj6pKwP3MnjlFSMxqV/NEq1FTpkVyl/oQDPwI+IUdbkNhkhljFXmbYWjz8ZtfJvKjEvIH73z+bkFYqdELYrP7WeycdRWHpRk2eDWZwrKLMFSJX0hjcmOaHfiatFO6ma6Gz34LTwxmvMh3e+fY1O/2inuv/aHf0VEZAZjjF/9zh8pPDpGblKDkDlVyIvf7ZEv6cV6RabAYFA/3xqqjNTyeniWzIF2HpA9g/EgYZO3KwJkzanJ0X6S/FX2UaPnAWMJ0q1GnwauQn0S2wVcN/6hub1oTUWnw2tIDaPFYfVLiuEBTTML8f/1+UW6E5wegaLCrjrDDwh5F5MaG3Lyy5qhv0YSC/j7cvomdlnwN5XV2ziNzTgdFTI3KSbguNoqH0IPNvpyQ2mc/9Jo32SXVSqn+NYXYIfGF9G3cO76bUMCyWo75y4YKEBR4Ud0BUzOD82L/HD9YcA5tqd3gHhta2Zpa7Nf3iKegw804X+qwrNHCXgk0tupB5v/ku3Af2VRRX2064=
  app: mailer-worker
  skip_cleanup: true
